name: CI

on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test run

  build:
    if: github.ref_name == 'main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check
        with:
          file-name: ./packages/contrast/package.json

      - name: Install pnpm
        if: steps.check.outputs.changed == 'true'
        uses: pnpm/action-setup@v2

      - name: Set node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        if: steps.check.outputs.changed == 'true'
        run: pnpm install --frozen-lockfile

      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: pnpm build --filter wcag-contrast-util

      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: pnpm publish --dry-run --filter wcag-contrast-util
